[pytest]
# addopts: Opciones automáticas
# --slowmo 500: Retraso para que el ojo humano lo siga
# --browser chromium: El motor que vamos a usar
addopts = --slowmo 500 --browser chromium
testpaths = tests